### ISSUE TITLE
Classes and IDs

### ISSUE THREAD

**Issue by stevetoro** [mscanza/tea-cozy#4]
https://github.com/mscanza/tea-cozy/blob/master/index.html#L38-L82

Avoid redundant class names.

You shouldn't need to append `-image` to a class name, because an `img` tag would be sufficient to indicate that there's an image present. The class `tea` should suffice.

You shouldn't need to append `-box` to a class name, because everything in HTML is a box. Leave it was `location` instead.

**Comment by mscanza** [comment]
Thank you Steve, changes have been implemented.
